// This is the Token (tok(746F)) for the tokens that is incorperated in LyraStandards. 
// This standard is designed to warn and become a normal check to ensure that rules are followed
// and in a strong effort to eliminate as many scammers from coming into the chain.
// Lyra, the honest chain.


 #[derive(Debug, PartialEq)]
pub struct TokenStd {
    id: String, //this will also be generated by a hash/ ID generator later.
    is_standard: bool,
    has_total_supply: bool,
    has_max_supply: bool,
    can_transfer: bool
}

impl TokenStd {

    pub fn new_token_std(id: String) -> TokenStd {
        let token_standard = TokenStd {
            id: id,
            is_standard: true,
            has_total_supply: true,
            has_max_supply: true,
            can_transfer: true
        };
        return token_standard;
    }









}
