// This is the Token (tok(746F)) for the tokens that is incorperated in LyraStandards. 
// This standard is designed to warn and become a normal check to ensure that rules are followed
// and in a strong effort to eliminate as many scammers from coming into the chain.
// Lyra, the honest chain.
pub use serde_derive::Deserialize;

#[derive(serde_derive::Serialize, Deserialize, Debug, PartialEq, Clone)] 

pub struct TokenStd {
    id: String, //this will also be generated by a hash/ ID generator later. for proof of no
                //changes, perhaps we make this a hash of the token value as well as this standard
                //so we can see if this hash matches the current state?
    is_std: bool,
    has_fixed_supply: bool, 
    can_transfer: bool
}

impl TokenStd {

    pub fn new_token_std(id: String) -> TokenStd {
        let token_standard = TokenStd {
            id: id,
            is_std: true,
            has_fixed_supply: true, 
            can_transfer: true
        };
        return token_standard;
    }

    pub fn is_following_token_std(token_std: TokenStd) -> bool {
        let std = TokenStd {
            id: "id".to_string(),
            is_std: true,
            has_fixed_supply: true,
            can_transfer: true
        };
        if std.is_std == token_std.is_std && std.has_fixed_supply == token_std.has_fixed_supply &&
            std.can_transfer == token_std.can_transfer {
                return true
        } else {
            return false
        }
    }

    pub fn get_has_totsup(tokenStd: &TokenStd) -> bool {
        return tokenStd.has_fixed_supply;
    
    }







}
